import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../features/settings/providers/settings_provider.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    // Sidebar & Navigation
    'dashboard': {'ms': 'Dashboard', 'en': 'Dashboard'},
    'program': {'ms': 'Program', 'en': 'Programs'},
    'certificate_verification': {'ms': 'Pengesahan Sijil', 'en': 'Certificate Verification'},
    'counter_registration': {'ms': 'Pendaftaran Kaunter', 'en': 'Counter Registration'},
    'settings': {'ms': 'Tetapan', 'en': 'Settings'},
    'main_menu': {'ms': 'MENU UTAMA', 'en': 'MAIN MENU'},
    'others': {'ms': 'LAIN-LAIN', 'en': 'OTHERS'},
    'system_sijil': {'ms': 'Sistem Sijil', 'en': 'Certificate System'},
    'certificate_management': {'ms': 'Pengurusan Sijil', 'en': 'Certificate Management'},

    // Counter Registration
    'counter_registration_desc': {'ms': 'Daftar peserta secara langsung di kaunter event', 'en': 'Register participants directly at the event counter'},
    'registration_form': {'ms': 'Borang Pendaftaran', 'en': 'Registration Form'},
    'select_program': {'ms': 'Pilih Program', 'en': 'Select Program'},
    'choose_program': {'ms': 'Pilih program...', 'en': 'Choose program...'},
    'full_name': {'ms': 'Nama Penuh', 'en': 'Full Name'},
    'full_name_hint': {'ms': 'Masukkan nama penuh seperti dalam IC', 'en': 'Enter full name as per IC'},
    'ic_number': {'ms': 'No. Kad Pengenalan', 'en': 'IC Number'},
    'ic_number_hint': {'ms': 'Contoh: 901234567890', 'en': 'Example: 901234567890'},
    'email': {'ms': 'Emel', 'en': 'Email'},
    'email_hint': {'ms': 'Contoh: nama@email.com', 'en': 'Example: name@email.com'},
    'optional': {'ms': 'Pilihan', 'en': 'Optional'},
    'register': {'ms': 'Daftar', 'en': 'Register'},
    'clear': {'ms': 'Kosongkan', 'en': 'Clear'},
    'please_enter_name': {'ms': 'Sila masukkan nama', 'en': 'Please enter name'},
    'please_enter_ic': {'ms': 'Sila masukkan No. IC', 'en': 'Please enter IC number'},
    'ic_must_12_digits': {'ms': 'No. IC mesti 12 digit', 'en': 'IC number must be 12 digits'},
    'selected_program': {'ms': 'Program Dipilih', 'en': 'Selected Program'},
    'today_registrations': {'ms': 'Pendaftaran Hari Ini', 'en': 'Today Registrations'},
    'recent_registrations': {'ms': 'Pendaftaran Terkini', 'en': 'Recent Registrations'},
    'select_program_first': {'ms': 'Pilih program untuk mula', 'en': 'Select a program to start'},
    'no_registrations_today': {'ms': 'Belum ada pendaftaran hari ini', 'en': 'No registrations today yet'},
    'please_select_program_first': {'ms': 'Sila pilih program terlebih dahulu', 'en': 'Please select a program first'},
    'participant_already_registered': {'ms': 'Peserta dengan No. IC ini sudah didaftarkan untuk program ini', 'en': 'Participant with this IC number is already registered for this program'},
    'registration_error': {'ms': 'Ralat semasa pendaftaran', 'en': 'Error during registration'},
    'registration_success': {'ms': 'Pendaftaran berjaya untuk', 'en': 'Registration successful for'},

    // Dashboard
    'welcome': {'ms': 'Selamat Datang!', 'en': 'Welcome!'},
    'manage_certificates_easily': {'ms': 'Urus sijil anda dengan mudah dan pantas', 'en': 'Manage your certificates easily and quickly'},
    'new_program': {'ms': 'Program Baru', 'en': 'New Program'},
    'total_programs': {'ms': 'Jumlah Program', 'en': 'Total Programs'},
    'total_participants': {'ms': 'Jumlah Peserta', 'en': 'Total Participants'},
    'certificates_generated': {'ms': 'Sijil Dijana', 'en': 'Certificates Generated'},
    'recent_programs': {'ms': 'Program Terkini', 'en': 'Recent Programs'},
    'view_all': {'ms': 'Lihat Semua', 'en': 'View All'},
    'no_programs': {'ms': 'Tiada Program', 'en': 'No Programs'},
    'start_first_program': {'ms': 'Mulakan dengan mencipta program pertama anda', 'en': 'Start by creating your first program'},
    'create_program': {'ms': 'Cipta Program', 'en': 'Create Program'},
    'participants': {'ms': 'peserta', 'en': 'participants'},
    'no_organizer': {'ms': 'Tiada penganjur', 'en': 'No organizer'},
    'completed': {'ms': 'Selesai', 'en': 'Completed'},
    'in_progress': {'ms': 'Dalam Proses', 'en': 'In Progress'},
    'not_started': {'ms': 'Belum Mula', 'en': 'Not Started'},

    // Settings
    'settings_title': {'ms': 'Tetapan', 'en': 'Settings'},
    'manage_app_settings': {'ms': 'Urus tetapan aplikasi dan data', 'en': 'Manage application settings and data'},
    'appearance': {'ms': 'Penampilan', 'en': 'Appearance'},
    'language': {'ms': 'Bahasa / Language', 'en': 'Language'},
    'security': {'ms': 'Keselamatan', 'en': 'Security'},
    'password_lock': {'ms': 'Kunci Kata Laluan', 'en': 'Password Lock'},
    'active': {'ms': 'Aktif', 'en': 'Active'},
    'inactive': {'ms': 'Tidak aktif', 'en': 'Inactive'},
    'change_password': {'ms': 'Tukar Kata Laluan', 'en': 'Change Password'},
    'update_password': {'ms': 'Kemaskini kata laluan anda', 'en': 'Update your password'},
    'backup_restore': {'ms': 'Sandaran & Pemulihan', 'en': 'Backup & Restore'},
    'backup_desc': {'ms': 'Buat sandaran data untuk simpan di tempat lain atau pulihkan data dari sandaran sebelumnya.', 'en': 'Create a backup to save elsewhere or restore data from a previous backup.'},
    'create_backup': {'ms': 'Buat Sandaran', 'en': 'Create Backup'},
    'creating_backup': {'ms': 'Membuat sandaran...', 'en': 'Creating backup...'},
    'restore_data': {'ms': 'Pulihkan Data', 'en': 'Restore Data'},
    'restoring': {'ms': 'Memulihkan...', 'en': 'Restoring...'},
    'online_verification': {'ms': 'Pengesahan Online', 'en': 'Online Verification'},
    'verification_url_desc': {'ms': 'Masukkan URL Google Apps Script untuk QR code verification. Scan QR pada sijil akan terus buka halaman pengesahan.', 'en': 'Enter Google Apps Script URL for QR code verification. Scanning QR on certificate will open verification page.'},
    'verification_url_label': {'ms': 'URL Pengesahan (Apps Script)', 'en': 'Verification URL (Apps Script)'},
    'save_url': {'ms': 'Simpan URL', 'en': 'Save URL'},
    'saving': {'ms': 'Menyimpan...', 'en': 'Saving...'},
    'csv_setup_guide': {'ms': 'Fail CSV & Panduan Setup', 'en': 'CSV Files & Setup Guide'},
    'open_csv_folder': {'ms': 'Buka Folder CSV', 'en': 'Open CSV Folder'},
    'setup_guide': {'ms': 'Panduan Setup', 'en': 'Setup Guide'},
    'about_app': {'ms': 'Tentang Aplikasi', 'en': 'About App'},
    'app_version': {'ms': 'Versi Aplikasi', 'en': 'App Version'},
    'built_with': {'ms': 'Dibina dengan', 'en': 'Built with'},
    'data_storage': {'ms': 'Storan Data', 'en': 'Data Storage'},

    // Dialogs
    'cancel': {'ms': 'Batal', 'en': 'Cancel'},
    'save': {'ms': 'Simpan', 'en': 'Save'},
    'delete': {'ms': 'Padam', 'en': 'Delete'},
    'confirm': {'ms': 'Sahkan', 'en': 'Confirm'},
    'set_password': {'ms': 'Tetapkan Kata Laluan', 'en': 'Set Password'},
    'enter_new_password': {'ms': 'Masukkan kata laluan baru', 'en': 'Enter new password'},
    'password': {'ms': 'Kata Laluan', 'en': 'Password'},
    'old_password': {'ms': 'Kata Laluan Lama', 'en': 'Old Password'},
    'new_password': {'ms': 'Kata Laluan Baru', 'en': 'New Password'},
    'restore_data_confirm': {'ms': 'Pulihkan Data?', 'en': 'Restore Data?'},
    'restore_warning': {'ms': 'Ini akan menggantikan semua data sedia ada. Pastikan anda telah membuat sandaran terlebih dahulu.', 'en': 'This will replace all existing data. Make sure you have created a backup first.'},
    'restore': {'ms': 'Pulihkan', 'en': 'Restore'},
    'understand': {'ms': 'Faham', 'en': 'Understand'},

    // Messages
    'password_set_success': {'ms': 'Kata laluan berjaya ditetapkan!', 'en': 'Password set successfully!'},
    'password_changed_success': {'ms': 'Kata laluan berjaya ditukar!', 'en': 'Password changed successfully!'},
    'old_password_incorrect': {'ms': 'Kata laluan lama tidak betul', 'en': 'Old password is incorrect'},
    'backup_success': {'ms': 'Sandaran berjaya disimpan', 'en': 'Backup saved successfully'},
    'restore_success': {'ms': 'Data berjaya dipulihkan!', 'en': 'Data restored successfully!'},
    'url_must_https': {'ms': 'URL mesti bermula dengan https://', 'en': 'URL must start with https://'},
    'url_deleted': {'ms': 'URL dipadamkan. QR akan guna format JSON.', 'en': 'URL deleted. QR will use JSON format.'},
    'url_saved': {'ms': 'URL disimpan! QR code akan mengandungi link verification.', 'en': 'URL saved! QR code will contain verification link.'},
    'folder_opened': {'ms': 'Folder dibuka', 'en': 'Folder opened'},
    'error': {'ms': 'Ralat', 'en': 'Error'},

    // Programs
    'programs': {'ms': 'Program', 'en': 'Programs'},
    'program_list': {'ms': 'Senarai Program', 'en': 'Program List'},
    'add_program': {'ms': 'Tambah Program', 'en': 'Add Program'},
    'edit_program': {'ms': 'Edit Program', 'en': 'Edit Program'},
    'delete_program': {'ms': 'Padam Program', 'en': 'Delete Program'},
    'delete_program_confirm': {'ms': 'Padam Program?', 'en': 'Delete Program?'},
    'delete_program_warning': {'ms': 'Semua data peserta dan sijil akan dipadam.', 'en': 'All participant data and certificates will be deleted.'},
    'program_name': {'ms': 'Nama Program', 'en': 'Program Name'},
    'organizer': {'ms': 'Penganjur', 'en': 'Organizer'},
    'download_template': {'ms': 'Muat Turun Template', 'en': 'Download Template'},

    // Participants
    'participant_list': {'ms': 'Senarai Peserta', 'en': 'Participant List'},
    'search_participant': {'ms': 'Cari peserta...', 'en': 'Search participant...'},
    'no_participants': {'ms': 'Tiada Peserta', 'en': 'No Participants'},
    'import_participants_hint': {'ms': 'Import senarai peserta dari fail Excel untuk mula', 'en': 'Import participant list from Excel file to start'},
    'selected': {'ms': 'dipilih', 'en': 'selected'},
    'generate_certificate': {'ms': 'Jana Sijil', 'en': 'Generate Certificate'},
    'generate_all_certificates': {'ms': 'Jana Semua Sijil', 'en': 'Generate All Certificates'},
    'regenerate_certificates': {'ms': 'Jana Semula Sijil', 'en': 'Regenerate Certificates'},
    'regenerate_all_certificates': {'ms': 'Jana Semula Semua Sijil', 'en': 'Regenerate All Certificates'},
    'regenerating': {'ms': 'Sedang menjana semula...', 'en': 'Regenerating...'},
    'regenerate_confirm_title': {'ms': 'Jana Semula Sijil?', 'en': 'Regenerate Certificates?'},
    'regenerate_confirm_message': {'ms': 'Ini akan menjana semula sijil yang dipilih dengan tetapan terkini. Sijil lama akan diganti.', 'en': 'This will regenerate selected certificates with current settings. Old certificates will be replaced.'},
    'regenerate_success': {'ms': 'sijil berjaya dijana semula!', 'en': 'certificates regenerated successfully!'},
    'no_certificates_to_regenerate': {'ms': 'Tiada sijil untuk dijana semula', 'en': 'No certificates to regenerate'},
    'combine_all_pdf': {'ms': 'Gabung Semua PDF', 'en': 'Combine All PDF'},
    'select_all': {'ms': 'Pilih Semua', 'en': 'Select All'},
    'import_data': {'ms': 'Import Data', 'en': 'Import Data'},
    'import_excel_desc': {'ms': 'Import senarai peserta dari fail Excel', 'en': 'Import participant list from Excel file'},
    'import_excel': {'ms': 'Import Excel', 'en': 'Import Excel'},
    'quick_actions': {'ms': 'Tindakan Pantas', 'en': 'Quick Actions'},
    'certificate': {'ms': 'Sijil', 'en': 'Certificate'},
    'certificate_exists': {'ms': 'Sijil Ada', 'en': 'Has Certificate'},
    'view_certificate': {'ms': 'Lihat Sijil', 'en': 'View Certificate'},
    'participants_imported': {'ms': 'peserta berjaya diimport!', 'en': 'participants imported successfully!'},
    'template_saved': {'ms': 'Template disimpan', 'en': 'Template saved'},
    'certificates_generated_success': {'ms': 'sijil berjaya dijana!', 'en': 'certificates generated successfully!'},
    'certificate_generated_for': {'ms': 'Sijil untuk', 'en': 'Certificate for'},
    'generated_success': {'ms': 'berjaya dijana!', 'en': 'generated successfully!'},
    'combining_certificates': {'ms': 'Menggabungkan', 'en': 'Combining'},
    'certificates_word': {'ms': 'sijil...', 'en': 'certificates...'},

    // Verification
    'verify_certificate': {'ms': 'Sahkan Sijil', 'en': 'Verify Certificate'},
    'enter_cert_number': {'ms': 'Masukkan nombor sijil', 'en': 'Enter certificate number'},
    'verify': {'ms': 'Sahkan', 'en': 'Verify'},
    'valid_certificate': {'ms': 'SIJIL SAH', 'en': 'VALID CERTIFICATE'},
    'invalid_certificate': {'ms': 'SIJIL TIDAK SAH', 'en': 'INVALID CERTIFICATE'},
    'certificate_authentic': {'ms': 'Sijil ini adalah asli dan sah', 'en': 'This certificate is authentic and valid'},
    'certificate_not_verified': {'ms': 'Sijil tidak dapat disahkan', 'en': 'Certificate could not be verified'},
    'certificate_not_found': {'ms': 'Sijil tidak dijumpai dalam sistem', 'en': 'Certificate not found in system'},
    'verification_code': {'ms': 'Kod Pengesahan', 'en': 'Verification Code'},
    'verification_code_hint': {'ms': 'Contoh: CERT-2024-001 atau kod dari QR', 'en': 'Example: CERT-2024-001 or code from QR'},
    'verifying': {'ms': 'Mengesahkan...', 'en': 'Verifying...'},
    'no_verification': {'ms': 'Tiada Pengesahan', 'en': 'No Verification'},
    'enter_code_to_verify': {'ms': 'Masukkan kod sijil untuk mula mengesahkan', 'en': 'Enter certificate code to start verifying'},
    'verify_authenticity': {'ms': 'Sahkan keaslian sijil menggunakan kod atau nombor sijil', 'en': 'Verify certificate authenticity using code or certificate number'},
    'enter_qr_or_number': {'ms': 'Masukkan kod QR atau nombor sijil', 'en': 'Enter QR code or certificate number'},
    'certificate_info': {'ms': 'Maklumat Sijil', 'en': 'Certificate Information'},
    'certificate_number': {'ms': 'Nombor Sijil', 'en': 'Certificate Number'},
    'participant_name': {'ms': 'Nama Peserta', 'en': 'Participant Name'},
    'issue_date': {'ms': 'Tarikh Pengeluaran', 'en': 'Issue Date'},
    'times_verified': {'ms': 'Kali Disahkan', 'en': 'Times Verified'},
    'times': {'ms': 'kali', 'en': 'times'},
    'please_enter_code': {'ms': 'Sila masukkan kod pengesahan', 'en': 'Please enter verification code'},

    // Programs List (additional)
    'programs_found': {'ms': 'program dijumpai', 'en': 'programs found'},
    'search_program': {'ms': 'Cari program...', 'en': 'Search program...'},
    'filter': {'ms': 'Filter', 'en': 'Filter'},
    'sort': {'ms': 'Susun', 'en': 'Sort'},
    'no_results': {'ms': 'Tiada Hasil', 'en': 'No Results'},
    'try_other_keywords': {'ms': 'Cuba kata kunci lain', 'en': 'Try other keywords'},
    'create_first_program': {'ms': 'Cipta program pertama anda untuk mula menjana sijil', 'en': 'Create your first program to start generating certificates'},
    'view': {'ms': 'Lihat', 'en': 'View'},
    'edit': {'ms': 'Edit', 'en': 'Edit'},
    'participant_word': {'ms': 'Peserta', 'en': 'Participants'},
    'certificate_word': {'ms': 'Sijil', 'en': 'Certificates'},
    'delete_program_question': {'ms': 'Padam Program?', 'en': 'Delete Program?'},
    'delete_confirm_message': {'ms': 'Adakah anda pasti mahu memadam', 'en': 'Are you sure you want to delete'},
    'action_cannot_undone': {'ms': 'Tindakan ini tidak boleh dibatalkan.', 'en': 'This action cannot be undone.'},

    // Program Detail (additional)
    'back': {'ms': 'Kembali', 'en': 'Back'},
    'all_data_deleted': {'ms': 'Semua data peserta dan sijil akan dipadam.', 'en': 'All participant data and certificates will be deleted.'},
    'import_excel_hint': {'ms': 'Import senarai peserta dari fail Excel', 'en': 'Import participant list from Excel file'},
    'imported_success': {'ms': 'berjaya diimport!', 'en': 'imported successfully!'},
    'error_prefix': {'ms': 'Ralat', 'en': 'Error'},

    // Program Create/Edit Form
    'new_program_title': {'ms': 'Program Baru', 'en': 'New Program'},
    'edit_program_title': {'ms': 'Edit Program', 'en': 'Edit Program'},
    'fill_program_info': {'ms': 'Isi maklumat untuk mencipta program baru', 'en': 'Fill in the information to create a new program'},
    'update_program_info': {'ms': 'Kemaskini maklumat program', 'en': 'Update program information'},
    'program_info': {'ms': 'Maklumat Program', 'en': 'Program Information'},
    'program_name_label': {'ms': 'Nama Program', 'en': 'Program Name'},
    'program_name_hint': {'ms': 'Contoh: Kursus Pengurusan Data', 'en': 'Example: Data Management Course'},
    'please_enter_program_name': {'ms': 'Sila masukkan nama program', 'en': 'Please enter program name'},
    'organizer_name': {'ms': 'Nama Penganjur', 'en': 'Organizer Name'},
    'organizer_hint': {'ms': 'Contoh: Majlis Perbandaran Sibu', 'en': 'Example: Sibu Municipal Council'},
    'organizer_tagline': {'ms': 'Tagline Penganjur (Pilihan)', 'en': 'Organizer Tagline (Optional)'},
    'organizer_tagline_hint': {'ms': 'Contoh: Berkhidmat Untuk Rakyat', 'en': 'Example: Serving the People'},
    'issue_date_label': {'ms': 'Tarikh Pengeluaran', 'en': 'Issue Date'},
    'signatory_info': {'ms': 'Maklumat Penandatangan', 'en': 'Signatory Information'},
    'signatory_name': {'ms': 'Nama Penandatangan', 'en': 'Signatory Name'},
    'signatory_name_hint': {'ms': 'Contoh: Mr Hisham', 'en': 'Example: Mr Hisham'},
    'signatory_title': {'ms': 'Jawatan Penandatangan', 'en': 'Signatory Title'},
    'signatory_title_hint': {'ms': 'Contoh: Pengarah Program', 'en': 'Example: Program Director'},
    'logo_signature': {'ms': 'Logo & Tandatangan', 'en': 'Logo & Signature'},
    'organizer_logo': {'ms': 'Logo Penganjur', 'en': 'Organizer Logo'},
    'signature': {'ms': 'Tandatangan', 'en': 'Signature'},
    'click_to_upload': {'ms': 'Klik untuk muat naik', 'en': 'Click to upload'},
    'certificate_type': {'ms': 'Jenis Sijil', 'en': 'Certificate Type'},
    'cert_participation': {'ms': 'Sijil Penyertaan', 'en': 'Certificate of Participation'},
    'cert_appreciation': {'ms': 'Sijil Penghargaan', 'en': 'Certificate of Appreciation'},
    'cert_achievement': {'ms': 'Sijil Pencapaian', 'en': 'Certificate of Achievement'},
    'cert_attendance': {'ms': 'Sijil Kehadiran', 'en': 'Certificate of Attendance'},
    'certificate_template': {'ms': 'Template Sijil', 'en': 'Certificate Template'},
    'template_modern': {'ms': 'Moden', 'en': 'Modern'},
    'template_classic': {'ms': 'Klasik', 'en': 'Classic'},
    'template_formal': {'ms': 'Formal', 'en': 'Formal'},
    'template_creative': {'ms': 'Kreatif', 'en': 'Creative'},
    'certificate_language': {'ms': 'Bahasa Sijil', 'en': 'Certificate Language'},
    'show_ic_number': {'ms': 'Papar No. Kad Pengenalan', 'en': 'Show IC Number'},
    'show_ic_number_desc': {'ms': 'Paparkan nombor IC peserta pada sijil', 'en': 'Display participant IC number on certificate'},
    'bilingual': {'ms': 'Dwibahasa (BM & EN)', 'en': 'Bilingual (BM & EN)'},
    'malay_only': {'ms': 'Bahasa Melayu', 'en': 'Malay'},
    'english_only': {'ms': 'English', 'en': 'English'},
    'update': {'ms': 'Kemaskini', 'en': 'Update'},
    'save_btn': {'ms': 'Simpan', 'en': 'Save'},
    'program_updated': {'ms': 'Program dikemaskini!', 'en': 'Program updated!'},
    'program_created': {'ms': 'Program dicipta!', 'en': 'Program created!'},
    'generating': {'ms': 'Menggabungkan', 'en': 'Combining'},
    'certificates_suffix': {'ms': 'sijil...', 'en': 'certificates...'},
    'certificate_for': {'ms': 'Sijil untuk', 'en': 'Certificate for'},
    'success_generated': {'ms': 'berjaya dijana!', 'en': 'successfully generated!'},

    // Login Screen
    'enter_password': {'ms': 'Masukkan Kata Laluan', 'en': 'Enter Password'},
    'password_hint': {'ms': 'Kata laluan', 'en': 'Password'},
    'login': {'ms': 'Masuk', 'en': 'Login'},
    'wrong_password': {'ms': 'Kata laluan salah', 'en': 'Wrong password'},
    'welcome_back': {'ms': 'Selamat Kembali', 'en': 'Welcome Back'},
    'enter_password_to_continue': {'ms': 'Masukkan kata laluan untuk meneruskan', 'en': 'Enter password to continue'},

    // Factory Reset
    'factory_reset': {'ms': 'Set Semula Kilang', 'en': 'Factory Reset'},
    'factory_reset_desc': {'ms': 'Padam semua data dan kembalikan aplikasi ke tetapan asal. Tindakan ini tidak boleh dibatalkan.', 'en': 'Delete all data and restore application to default settings. This action cannot be undone.'},
    'reset_now': {'ms': 'Set Semula Sekarang', 'en': 'Reset Now'},
    'resetting': {'ms': 'Memadam data...', 'en': 'Deleting data...'},
    'factory_reset_confirm': {'ms': 'Set Semula Kilang?', 'en': 'Factory Reset?'},
    'factory_reset_warning': {'ms': 'AMARAN: Semua data akan dipadam termasuk:', 'en': 'WARNING: All data will be deleted including:'},
    'all_programs': {'ms': 'Semua program', 'en': 'All programs'},
    'all_participants': {'ms': 'Semua peserta', 'en': 'All participants'},
    'all_certificates': {'ms': 'Semua sijil', 'en': 'All certificates'},
    'all_settings': {'ms': 'Semua tetapan', 'en': 'All settings'},
    'type_confirm': {'ms': 'Taip "PADAM" untuk sahkan:', 'en': 'Type "DELETE" to confirm:'},
    'confirm_word_ms': {'ms': 'PADAM', 'en': 'PADAM'},
    'confirm_word_en': {'ms': 'DELETE', 'en': 'DELETE'},
    'factory_reset_success': {'ms': 'Set semula kilang berjaya! Aplikasi akan dimulakan semula.', 'en': 'Factory reset successful! Application will restart.'},
    'wrong_confirm_word': {'ms': 'Perkataan pengesahan tidak betul', 'en': 'Confirmation word is incorrect'},

    // Online Verification Guide
    'online_verification_guide': {'ms': 'Panduan Pengesahan Online', 'en': 'Online Verification Guide'},
    'step': {'ms': 'Langkah', 'en': 'Step'},
    'export_cert_data': {'ms': 'Export Data Sijil', 'en': 'Export Certificate Data'},
    'export_csv_hint': {'ms': 'Klik butang "Export Data Sijil" untuk muat turun fail CSV.', 'en': 'Click "Export Certificate Data" button to download CSV file.'},
    'create_google_sheets': {'ms': 'Buat Google Sheets', 'en': 'Create Google Sheets'},
    'google_sheets_hint': {'ms': 'Buka Google Sheets (sheets.google.com) dan import fail CSV.', 'en': 'Open Google Sheets (sheets.google.com) and import the CSV file.'},
    'setup_apps_script': {'ms': 'Setup Apps Script', 'en': 'Setup Apps Script'},
    'apps_script_hint': {'ms': 'Pergi ke Extensions > Apps Script dan paste kod dari fail "apps_script.js" yang disertakan.', 'en': 'Go to Extensions > Apps Script and paste the code from the included "apps_script.js" file.'},
    'deploy_web_app': {'ms': 'Deploy Web App', 'en': 'Deploy Web App'},
    'deploy_hint': {'ms': 'Klik Deploy > New deployment > Web app. Set "Who has access" kepada "Anyone".', 'en': 'Click Deploy > New deployment > Web app. Set "Who has access" to "Anyone".'},
    'share_link': {'ms': 'Kongsi Link', 'en': 'Share Link'},
    'share_link_hint': {'ms': 'Salin URL deployment dan kongsi untuk pengesahan sijil online.', 'en': 'Copy the deployment URL and share for online certificate verification.'},
    'guide_note': {'ms': 'Fail panduan lengkap dan kod Apps Script disertakan dalam folder export.', 'en': 'Complete guide file and Apps Script code are included in the export folder.'},

    // Cloud Backup
    'cloud_backup': {'ms': 'Sandaran Cloud', 'en': 'Cloud Backup'},
    'cloud_backup_desc': {'ms': 'Simpan sandaran data ke Google Drive atau OneDrive untuk akses di mana-mana.', 'en': 'Save backup data to Google Drive or OneDrive for access anywhere.'},
    'google_drive': {'ms': 'Google Drive', 'en': 'Google Drive'},
    'onedrive': {'ms': 'OneDrive', 'en': 'OneDrive'},
    'sign_in': {'ms': 'Log Masuk', 'en': 'Sign In'},
    'sign_out': {'ms': 'Log Keluar', 'en': 'Sign Out'},
    'signed_in': {'ms': 'Telah Log Masuk', 'en': 'Signed In'},
    'not_signed_in': {'ms': 'Belum Log Masuk', 'en': 'Not Signed In'},
    'backup_to_cloud': {'ms': 'Backup ke Cloud', 'en': 'Backup to Cloud'},
    'restore_from_cloud': {'ms': 'Pulihkan dari Cloud', 'en': 'Restore from Cloud'},
    'view_backups': {'ms': 'Lihat Sandaran', 'en': 'View Backups'},
    'cloud_backups': {'ms': 'Sandaran Cloud', 'en': 'Cloud Backups'},
    'no_backups': {'ms': 'Tiada sandaran dijumpai', 'en': 'No backups found'},
    'backup_date': {'ms': 'Tarikh Sandaran', 'en': 'Backup Date'},
    'file_size': {'ms': 'Saiz Fail', 'en': 'File Size'},
    'delete_backup': {'ms': 'Padam Sandaran', 'en': 'Delete Backup'},
    'delete_backup_confirm': {'ms': 'Padam sandaran ini?', 'en': 'Delete this backup?'},
    'backup_deleted': {'ms': 'Sandaran dipadam', 'en': 'Backup deleted'},
    'uploading_backup': {'ms': 'Memuat naik sandaran...', 'en': 'Uploading backup...'},
    'downloading_backup': {'ms': 'Memuat turun sandaran...', 'en': 'Downloading backup...'},
    'backup_uploaded': {'ms': 'Sandaran berjaya dimuat naik!', 'en': 'Backup uploaded successfully!'},
    'backup_downloaded': {'ms': 'Sandaran berjaya dimuat turun!', 'en': 'Backup downloaded successfully!'},
    'sign_in_first': {'ms': 'Sila log masuk terlebih dahulu', 'en': 'Please sign in first'},
    'sign_in_success': {'ms': 'Log masuk berjaya!', 'en': 'Sign in successful!'},
    'sign_out_success': {'ms': 'Log keluar berjaya!', 'en': 'Sign out successful!'},
    'select_backup': {'ms': 'Pilih Sandaran', 'en': 'Select Backup'},
    'restore_this_backup': {'ms': 'Pulihkan sandaran ini?', 'en': 'Restore this backup?'},
    'close': {'ms': 'Tutup', 'en': 'Close'},
  };

  static String get(BuildContext context, String key) {
    final settings = context.read<SettingsProvider>();
    final lang = settings.language;
    return _strings[key]?[lang] ?? _strings[key]?['ms'] ?? key;
  }

  static String getByLang(String key, String lang) {
    return _strings[key]?[lang] ?? _strings[key]?['ms'] ?? key;
  }
}

String tr(BuildContext context, String key) => AppStrings.get(context, key);
